<?php
/**
 * Created by PhpStorm.
 * User: Think
 * Date: 2017/7/20
 * Time: 21:30
 */

namespace common\widgets;

use yii;
use yii\base\Widget;

/**
 * Class WeixinShare 微信分享小部件
 * @package common\widgets
 */
class WeixinShare extends  Widget
{
    /**
     * @var null 定义url 地址 分享的地址
     */
    public $url = null;

    /**
     * @var string 定义公众号的appId
     */
    public $appId = 'wx67e7d957689d27ef';

    /**
     * @var string 定义公众号的secret
     */
    public $appSecret = '0470be436f4e0b0a57487e747e0216f4';

    /**
     * @var array 分享信息
     */
    public $share = null;

    /**
     * @var array 定义配置信息
     */
    private $arrConfig;

    /**
     * @var string 定义获取access_token 地址信息
     */
    private $accessTokenUrl = 'https://api.weixin.qq.com/cgi-bin/token';

    /**
     * @var string 定义获取 jsapi_ticket 地址
     */
    private $jsApiTicketUrl = 'https://api.weixin.qq.com/cgi-bin/ticket/getticket';

    /**
     * @var string access_token 保存的redis 的key
     */
    private $strRedisAccessToken = 'CRM:weixin:access_token';

    /**
     * @var string jsapi_ticket 保存的redis 的 key
     */
    private $strRedisJsApiTicket = 'CRM:weixin:jsapi_ticket';

    /**
     * 初始化处理
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        // 定义地址信息
        if (!$this->url) {
            $request = Yii::$app->request;
            $this->url = $request->hostInfo.$request->getUrl();
        }

        // 处理应用配置信息
        if (isset(Yii::$app->params['weixin'])) {
            $this->appId = Yii::$app->params['weixin']['appId'];
            $this->appSecret = Yii::$app->params['weixin']['appSecret'];
        }

        // 获取配置信息
        $this->arrConfig = $this->getConfig($this->url);
    }

    public function run()
    {
        return $this->render('weixin', [
            'weixin' => $this->arrConfig, // 配置信息
            'share' => $this->share,      // 分享信息
        ]);
    }

    /**
     * 获取access_token
     *
     * @return mixed
     */
    public function getAccessToken()
    {
        /* @var $redis \yii\redis\Connection */
        $redis = Yii::$app->redis;
        $mixReturn = $redis->get($this->strRedisAccessToken);
        if (!$mixReturn) {
            $params = [
                'grant_type' => 'client_credential',
                'appid' => $this->appId,
                'secret' => $this->appSecret
            ];

            $response = file_get_contents($this->accessTokenUrl.'?'.http_build_query($params));
            if ($response) {
                $result = yii\helpers\Json::decode($response);
                if (isset($result['access_token'])) {
                    $mixReturn = $result['access_token'];
                    $redis->setex($this->strRedisAccessToken, 7200, $mixReturn);
                }
            }
        }

        return $mixReturn;
    }

    /**
     * 获取jsapi_ticket
     *
     * @param $strAccessToken
     * @return mixed
     */
    public function getJsApiTicket($strAccessToken)
    {
        /* @var $redis \yii\redis\Connection */
        $redis = Yii::$app->redis;
        $mixReturn = $redis->get($this->strRedisJsApiTicket);
        if (!$mixReturn) {
            $params = [
                'access_token' => $strAccessToken,
                'type' => 'jsapi',
            ];

            $response = file_get_contents($this->jsApiTicketUrl.'?'.http_build_query($params));
            if ($response) {
                $result = yii\helpers\Json::decode($response);
                if (isset($result['ticket'])) {
                    $mixReturn = $result['ticket'];
                    $redis->setex($this->strRedisJsApiTicket, 7200, $mixReturn);
                }
            }
        }

        return $mixReturn;

    }

    /**
     * 获取签名字符串
     *
     * @param int $length 字符串长度
     * @return string
     */
    public function getNonceStr($length = 16)
    {
        $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        $strNonceStr = '';
        $intNumber = strlen($chars) - 1;
        for ($i = 0; $i < $length; $i++) {
            $strNonceStr .= substr($chars, mt_rand(0, $intNumber), 1);
        }

        return $strNonceStr;
    }

    /**
     *  获取配置微信公众号的JS-SDK 的配置信息
     *
     * @param  string $url 页面地址信息
     * @return array
     */
    public function getConfig($url)
    {
        $accessToken = $this->getAccessToken();                 // 签名
        $strJsApiTicket = $this->getJsApiTicket($accessToken);  // jsapi_ticket
        $timestamp = time();                                    // 生成签名的时间戳
        $strNonceStr = $this->getNonceStr();                    // 随机签名字符串
        $string1 = 'jsapi_ticket='.$strJsApiTicket.'&noncestr='.$strNonceStr.'&timestamp='.$timestamp.'&url='.$url;
        $signature = sha1($string1);                            // 签名字符串

        // 返回配置信息
        return [
            'appId' => $this->appId,
            'nonceStr' => $strNonceStr,
            'timestamp' => $timestamp,
            'signature' => $signature,
            'url' => $url,
        ];
    }
}