<?php

namespace frontend\modules\sales\controllers;

use common\models\Clue;
use common\models\PutTheCar;
use yii;

/**
 * Class MentionTaskController 提车任务信息
 * @package frontend\modules\sales\controllers
 */
class MentionTaskController extends AuthController
{
    /**
     * 请求之前的处理
     * @param \yii\base\Action $action
     * @return bool
     */
    public function beforeAction($action)
    {
        $this->mixRequest = $this->getPData();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 接待提车客户列表
     *
     * @return array
     */
    public function actionLists()
    {
        /* @var $user \common\models\User */
        $user = Yii::$app->user->identity;

        // 查询条件是当前门店,没有完成的，没有分配的顾问任务
        $where = ['new_shop_id' => $user->shop_id, 'status' => PutTheCar::STATUS_UNDONE, 'new_salesman_id' => 0];
        $query = PutTheCar::find()->where($where);

        // 查询数据和分页信息
        $total = $query->count();
        $page = $this->getPage($this->mixRequest, $total);
        $arrReturn = [
            'pages' => $page['pages'],
            'models' => [],
        ];

        // 有数据才查询
        if ($total > 0) {
            $arrReturn['models'] = $query->select([
                'id',
                'clue_id',
                'old_salesman_name',
                'old_shop_name',
                'yu_ding_che_xing',
                'the_car_time',
                'confirm_time',
            ])->asArray()
                ->orderBy(['confirm_time' => SORT_DESC])
                ->offset($page['offset'])
                ->limit($page['limit'])
                ->all();

            // 获取到数据线索信息，查询线索，获取到最后联系时间
            if ($arrReturn['models']) {
                $arrClueIds = array_column($arrReturn['models'], 'clue_id');
                $clues = Clue::find()->select(['id', 'customer_name', 'customer_phone', 'last_view_time'])
                    ->where(['id' => $arrClueIds])->indexBy('id')->asArray()->all();
                foreach ($arrReturn['models'] as &$value) {
                    $value['last_view_time'] = 0;
                    $value['customer_name'] = '';
                    $value['customer_phone'] = '';

                    // 存在对应的线索信息
                    if (isset($clues[$value['clue_id']])) {
                        $value['last_view_time'] = (int)$clues[$value['clue_id']]['last_view_time'];
                        $value['customer_name'] = $clues[$value['clue_id']]['customer_name'];
                        $value['customer_phone'] = $clues[$value['clue_id']]['customer_phone'];
                    }

                    $value['id'] = (int)$value['id'];
                    $value['confirm_time'] = (int)$value['confirm_time'];
                    $value['the_car_time'] = (int)$value['the_car_time'];
                    $value['clue_id'] = (int)$value['clue_id'];
                }

                unset($value);
            }
        }

        return $arrReturn;
    }

    /**
     * 认领任务
     *
     * @return array
     */
    public function actionClaim()
    {
        $this->handleParams('请求参数为空');
        $arrReturn = [];
        $arrLogs = [
            'request' => $this->mixRequest,
        ];

        // 请求参数不能为空
        if (!empty($this->mixRequest['id'])) {
            /* @var $user \common\models\User */
            $user = Yii::$app->user->identity;
            $arrResult = PutTheCar::toClaim((int)$this->mixRequest['id'], $user);
            if ($arrResult['status'] === true && $arrResult['model']) {
                $this->handleParams('认领成功', 200);
            } else {
                $this->handleParams($arrResult['message']);
            }
        }

        // 记录日志返回
        $arrLogs['response'] = Yii::$app->params['message'];
        $this->writeLogs($arrLogs);
        return $arrReturn;
    }
}